spring:
  application:
    name: Inventory-Management-System

  # Allow graceful timeout period for 30 seconds
  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS IMS\;SET SCHEMA IMS
    username: sa
    password:
    driverClassName: org.h2.Driver

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  # Enable graceful shutdown
  shutdown: graceful


logging.level:
  org.springframework: INFO
  io.opentracing: TRACE
  io.jaegertracing: TRACE
  org.hibernate: INFO
  se.rsv: TRACE
  org.springdoc: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html