CREATE TABLE ARTICLE (
    "ID" VARCHAR(36) NOT NULL,
    "EXTERNAL_ID" VARCHAR(20) NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "IS_DELETED" INT DEFAULT 0,
    "LAST_UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE INVENTORY(
    "ID" VARCHAR(36) NOT NULL,
    "ARTICLE_ID" VARCHAR(36) NOT NULL,
    "QUANTITY" NUMBER
);

CREATE TABLE PRODUCT_CONFIGURATION(
    "ID" VARCHAR(36) NOT NULL,
    "PRODUCT_ID" VARCHAR(36) NOT NULL,
    "ARTICLE_ID" VARCHAR(36) NOT NULL,
    "ARTICLE_QUANTITY" NUMBER
);

CREATE TABLE PRODUCT(
    "ID" VARCHAR(36) NOT NULL,
    "EXTERNAL_ID" VARCHAR(20) NOT NULL,
    "NAME" VARCHAR(50) NOT NULL
);