CREATE TABLE INVENTORY(
    "ID" VARCHAR(36) NOT NULL,
    "ARTICLE_ID" VARCHAR(36) NOT NULL,
    "ARTICLE_NAME" VARCHAR(50),
    "STOCK" NUMBER
);

CREATE TABLE PRODUCT(
    "ID" VARCHAR(36) NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "ARTICLE_ID" VARCHAR(36) NOT NULL,
    "ARTICLE_QUANTITY" NUMBER
);